### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by EdgarWright** [smakosh/gatsby-portfolio-dev#5] opened 2019-06-02 10:47 UTC
Anyone else is getting this error?

GraphQL Error Encountered 1 error(s):
- Unknown field 'github' on type 'Query'. 

      file: ./gatsby-portfolio/new/gatsby-portfolio-dev/src/components/landing/Projects/index.jsx

**Comment by smakosh** [comment] 2019-06-06 02:00
Have you added the env variables mentioned on the docs?

**Comment by smakosh** [comment] 2019-06-08 10:14
The issue is caused by the `gatsby-source-graphql`, I provided more info to them, hopefully it will be fixed.

**Comment by smakosh** [comment] 2019-06-08 10:14
Meanwhile, downgrade your gatsby and gatsby-source-graphql to a previous version and give it a try.

**Comment by smakosh** [comment] 2019-06-10 00:59
Fixed here: https://github.com/gatsbyjs/gatsby/pull/14665

**Comment by smakosh** [comment] 2019-06-10 08:16
It has been fixed @EdgarWright

**Closed by smakosh** 2019-06-10 08:16 UTC

**Comment by marclundgren** [comment] 2019-07-12 02:01
I'm still experiencing the same problem when cloning the repo and running `yarn && yarn start` :/

**Comment by smakosh** [comment] 2019-07-12 02:59
I just tried and everything seems to work just fine. You probably forgot the GitHub token as env variable.
