### ISSUE TITLE
gatsby-plugin-favicon

### ISSUE THREAD

**Issue by carriepresley** [smakosh/gatsby-portfolio-dev#42] opened 2021-01-03 17:21 UTC
Everytime I try to run the development server I get an error with the favicon-plugin? Help. I'm a newbie, but I've been troubleshooting for a while and even after installing the plugin, I get the same error?

'There was a problem loading plugin "gatsby-plugin-favicon". Perhaps you need to install its package?
Use --verbose to see actual error.

 ERROR #10226  CONFIG'

**Comment by smakosh** [comment] 2021-01-03 17:50
I deleted the node modules locally and ran `yarn && yarn start` and everything seems to be working fine, can you share your node version?

**Comment by smakosh** [comment] 2021-01-03 17:56
Could you share your repository and I'll be able to help debug your issue

**Comment by carriepresley** [comment] 2021-01-03 17:59
Thank you smakosh! I just deleted and made a new one, thank you in advance!

**Comment by smakosh** [comment] 2021-01-03 18:08
Could you email me the env variables? or feel free to send them via [Keybase](https://keybase.io/app)

**Comment by smakosh** [comment] 2021-01-03 18:13
I cloned your example, used my env variables and it seems to be working fine, going to close this issue for now. Feel free to re-open if the issue is still persistent

**Comment by carriepresley** [comment] 2021-01-03 18:14
Thank you smakosh! I'll keep working on it... I appreciate you!

**Closed by smakosh** 2021-01-03 18:13 UTC
Labels: bug

**Comment by smakosh** [comment] 2021-01-03 18:26
Sure! anytime
